# Generated by Django 2.0.10 on 2019-07-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
